name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Vite app
      - name: Build
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
